const CARD_DATA = {
  "pack_cards": [
    {
      "id": "pack_189",
      "type": "pack",
      "brand": "中华",
      "name_cn": "中华（5支硬盒）",
      "origin": "上海",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/2020121821445402.png"
    },
    {
      "id": "pack_3299",
      "type": "pack",
      "brand": "中华",
      "name_cn": "中华（细支）",
      "origin": "上海",
      "format": "细支",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/2020050423192345.png"
    },
    {
      "id": "pack_2700",
      "type": "pack",
      "brand": "中华",
      "name_cn": "中华（双中支）",
      "origin": "上海",
      "format": "中支",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/2021021211042483.png"
    },
    {
      "id": "pack_3045",
      "type": "pack",
      "brand": "中华",
      "name_cn": "中华（听50支）",
      "origin": "上海",
      "format": "常规",
      "rarity": 5,
      "base_score": 7,
      "image_url": "https://ciggies.app/api/img/products/2018072721170729.png"
    },
    {
      "id": "pack_3630",
      "type": "pack",
      "brand": "中华",
      "name_cn": "中华（细支6mg）",
      "origin": "上海",
      "format": "细支",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/202509012150142130.jpg"
    },
    {
      "id": "pack_3689",
      "type": "pack",
      "brand": "玉溪",
      "name_cn": "玉溪（创客）",
      "origin": "云南",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202603110952420840.jpg"
    },
    {
      "id": "pack_3593",
      "type": "pack",
      "brand": "玉溪",
      "name_cn": "玉溪（细支缤果爆）",
      "origin": "云南",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202501230122516950.jpg"
    },
    {
      "id": "pack_3335",
      "type": "pack",
      "brand": "玉溪",
      "name_cn": "玉溪（鑫中支）",
      "origin": "云南",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2020080916453266.png"
    },
    {
      "id": "pack_3465",
      "type": "pack",
      "brand": "玉溪",
      "name_cn": "玉溪（中支钓鱼台）",
      "origin": "云南",
      "format": "中支",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/202210132244117800.jpg"
    },
    {
      "id": "pack_3683",
      "type": "pack",
      "brand": "玉溪",
      "name_cn": "玉溪（田园）",
      "origin": "云南",
      "format": "常规",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202507061855271520.jpg"
    },
    {
      "id": "pack_2923",
      "type": "pack",
      "brand": "芙蓉王",
      "name_cn": "芙蓉王（张家界）",
      "origin": "湖南",
      "format": "常规",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2017112000264373.png"
    },
    {
      "id": "pack_3650",
      "type": "pack",
      "brand": "芙蓉王",
      "name_cn": "芙蓉王（品悦细支）",
      "origin": "湖南",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202510292108379800.jpg"
    },
    {
      "id": "pack_3176",
      "type": "pack",
      "brand": "芙蓉王",
      "name_cn": "芙蓉王（硬中支）",
      "origin": "湖南",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202508022002591390.jpg"
    },
    {
      "id": "pack_3642",
      "type": "pack",
      "brand": "芙蓉王",
      "name_cn": "芙蓉王（绽放细支）",
      "origin": "湖南",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202510292103497820.jpg"
    },
    {
      "id": "pack_3448",
      "type": "pack",
      "brand": "芙蓉王",
      "name_cn": "芙蓉王（荣耀中支）",
      "origin": "湖南",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202508021428565200.jpg"
    },
    {
      "id": "pack_2615",
      "type": "pack",
      "brand": "黄鹤楼",
      "name_cn": "黄鹤楼（硬江城明珠）",
      "origin": "湖北",
      "format": "细支",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/20170126235011.png"
    },
    {
      "id": "pack_3148",
      "type": "pack",
      "brand": "黄鹤楼",
      "name_cn": "黄鹤楼（细支珍品）",
      "origin": "湖北",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2021030823023340.png"
    },
    {
      "id": "pack_3342",
      "type": "pack",
      "brand": "黄鹤楼",
      "name_cn": "黄鹤楼（金典中支）",
      "origin": "湖北",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2020093013214812.png"
    },
    {
      "id": "pack_3660",
      "type": "pack",
      "brand": "黄鹤楼",
      "name_cn": "黄鹤楼（漫天游九天）",
      "origin": "湖北",
      "format": "细支",
      "rarity": 5,
      "base_score": 7,
      "image_url": "https://ciggies.app/api/img/products/202512281852242240.jpg"
    },
    {
      "id": "pack_3654",
      "type": "pack",
      "brand": "黄鹤楼",
      "name_cn": "黄鹤楼（1916宝相细支）",
      "origin": "湖北",
      "format": "细支",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/202511200947210030.jpg"
    },
    {
      "id": "pack_875",
      "type": "pack",
      "brand": "利群",
      "name_cn": "利群（新版）",
      "origin": "浙江",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/2020122100350732.jpg"
    },
    {
      "id": "pack_3508",
      "type": "pack",
      "brand": "利群",
      "name_cn": "利群（阳光尊细支）",
      "origin": "浙江",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202305051038582910.jpg"
    },
    {
      "id": "pack_3628",
      "type": "pack",
      "brand": "利群",
      "name_cn": "利群（阳光中支）",
      "origin": "浙江",
      "format": "中支",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/202508252242087480.jpg"
    },
    {
      "id": "pack_3622",
      "type": "pack",
      "brand": "利群",
      "name_cn": "利群（阳光橙中支）",
      "origin": "浙江",
      "format": "中支",
      "rarity": 5,
      "base_score": 7,
      "image_url": "https://ciggies.app/api/img/products/202507192215479920.jpg"
    },
    {
      "id": "pack_3543",
      "type": "pack",
      "brand": "利群",
      "name_cn": "利群（山外山）",
      "origin": "浙江",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202401301531240650.jpg"
    },
    {
      "id": "pack_519",
      "type": "pack",
      "brand": "云烟",
      "name_cn": "云烟（珠光白）",
      "origin": "云南",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/20060317162553.jpg"
    },
    {
      "id": "pack_2347",
      "type": "pack",
      "brand": "云烟",
      "name_cn": "云烟（细支大重九）",
      "origin": "云南",
      "format": "细支",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/20160325134350.png"
    },
    {
      "id": "pack_3330",
      "type": "pack",
      "brand": "云烟",
      "name_cn": "云烟（中支乌镇之恋）",
      "origin": "云南",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2020071921573347.png"
    },
    {
      "id": "pack_3686",
      "type": "pack",
      "brand": "云烟",
      "name_cn": "云烟（细支醇萃）",
      "origin": "云南",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202603011413361100.jpg"
    },
    {
      "id": "pack_3684",
      "type": "pack",
      "brand": "云烟",
      "name_cn": "云烟（中支金腰带）",
      "origin": "云南",
      "format": "中支",
      "rarity": 5,
      "base_score": 7,
      "image_url": "https://ciggies.app/api/img/products/2018022723034664.png"
    },
    {
      "id": "pack_787",
      "type": "pack",
      "brand": "七匹狼",
      "name_cn": "七匹狼（睿典）",
      "origin": "福建",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/20070927225619.jpg"
    },
    {
      "id": "pack_2959",
      "type": "pack",
      "brand": "七匹狼",
      "name_cn": "七匹狼（金砖细支）",
      "origin": "福建",
      "format": "细支",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/2018020622155449.png"
    },
    {
      "id": "pack_3444",
      "type": "pack",
      "brand": "七匹狼",
      "name_cn": "七匹狼（古田成功中支）",
      "origin": "福建",
      "format": "中支",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/2022032112304846.png"
    },
    {
      "id": "pack_3678",
      "type": "pack",
      "brand": "七匹狼",
      "name_cn": "七匹狼（金典）",
      "origin": "福建",
      "format": "常规",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2021032801241605.png"
    },
    {
      "id": "pack_3652",
      "type": "pack",
      "brand": "七匹狼",
      "name_cn": "七匹狼（小金砖细支）",
      "origin": "福建",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202511092220067680.jpg"
    },
    {
      "id": "pack_3639",
      "type": "pack",
      "brand": "南京",
      "name_cn": "南京（大观园草本）",
      "origin": "江苏",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202509172215441180.jpg"
    },
    {
      "id": "pack_3598",
      "type": "pack",
      "brand": "白沙",
      "name_cn": "白沙（硬天天向上细支）",
      "origin": "湖南",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202504182223531680.jpg"
    },
    {
      "id": "pack_3649",
      "type": "pack",
      "brand": "白沙",
      "name_cn": "白沙（开心就好）",
      "origin": "湖南",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202510292056524440.jpg"
    },
    {
      "id": "pack_3277",
      "type": "pack",
      "brand": "苏烟",
      "name_cn": "苏烟（灵韵细支）",
      "origin": "江苏",
      "format": "细支",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/2020010419282838.png"
    },
    {
      "id": "pack_3377",
      "type": "pack",
      "brand": "苏烟",
      "name_cn": "苏烟（五星红中）",
      "origin": "江苏",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2021020518331961.png"
    },
    {
      "id": "pack_3450",
      "type": "pack",
      "brand": "黄金叶",
      "name_cn": "黄金叶（国色双中支）",
      "origin": "河南",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2022080120065243.png"
    },
    {
      "id": "pack_3682",
      "type": "pack",
      "brand": "黄金叶",
      "name_cn": "黄金叶（天香细支）",
      "origin": "河南",
      "format": "细支",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/20150127231317.jpg"
    },
    {
      "id": "pack_3623",
      "type": "pack",
      "brand": "黄金叶",
      "name_cn": "黄金叶（豫悦）",
      "origin": "河南",
      "format": "常规",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202507291133558440.jpg"
    },
    {
      "id": "pack_3484",
      "type": "pack",
      "brand": "黄山",
      "name_cn": "黄山（皖烟中支）",
      "origin": "安徽",
      "format": "中支",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/202301141249397390.png"
    },
    {
      "id": "pack_3428",
      "type": "pack",
      "brand": "钻石",
      "name_cn": "钻石（冬韵中支）",
      "origin": "河北",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2021120322063401.png"
    },
    {
      "id": "pack_3568",
      "type": "pack",
      "brand": "钻石",
      "name_cn": "钻石（荷花小雅90mm细支）",
      "origin": "河北",
      "format": "细支",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/202411031641083920.png"
    },
    {
      "id": "pack_3548",
      "type": "pack",
      "brand": "钻石",
      "name_cn": "钻石（84mm冬韵）",
      "origin": "河北",
      "format": "常规",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202402060109063770.jpg"
    },
    {
      "id": "pack_2637",
      "type": "pack",
      "brand": "泰山",
      "name_cn": "泰山（八仙过海细支）",
      "origin": "山东",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2021031911341187.png"
    },
    {
      "id": "pack_3549",
      "type": "pack",
      "brand": "泰山",
      "name_cn": "泰山（囍悦）",
      "origin": "山东",
      "format": "常规",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202402061435005060.png"
    },
    {
      "id": "pack_3298",
      "type": "pack",
      "brand": "双喜",
      "name_cn": "双喜（春天中支）",
      "origin": "广东",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2020050900022236.jpg"
    },
    {
      "id": "pack_3294",
      "type": "pack",
      "brand": "双喜",
      "name_cn": "双喜（春天细支）",
      "origin": "广东",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2020050900034539.jpg"
    },
    {
      "id": "pack_3670",
      "type": "pack",
      "brand": "双喜",
      "name_cn": "双喜（春天清风）",
      "origin": "广东",
      "format": "中支",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/202602042014587170.png"
    },
    {
      "id": "pack_3600",
      "type": "pack",
      "brand": "娇子",
      "name_cn": "娇子（格调中支）",
      "origin": "四川",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202504302040056160.jpg"
    },
    {
      "id": "pack_3669",
      "type": "pack",
      "brand": "娇子",
      "name_cn": "娇子（宽窄东坡细支）",
      "origin": "四川",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202602012048239620.png"
    },
    {
      "id": "pack_3582",
      "type": "pack",
      "brand": "娇子",
      "name_cn": "娇子（蓝时代）",
      "origin": "四川",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/202411221112360620.jpg"
    },
    {
      "id": "pack_3419",
      "type": "pack",
      "brand": "贵烟",
      "name_cn": "贵烟（福中支）",
      "origin": "贵州",
      "format": "中支",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/2021082320371563.png"
    },
    {
      "id": "pack_3044",
      "type": "pack",
      "brand": "贵烟",
      "name_cn": "贵烟（细支行者）",
      "origin": "贵州",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2018072720141179.png"
    },
    {
      "id": "pack_3572",
      "type": "pack",
      "brand": "贵烟",
      "name_cn": "贵烟（魔力新版）",
      "origin": "贵州",
      "format": "细支",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/202411051459282070.jpg"
    },
    {
      "id": "pack_3420",
      "type": "pack",
      "brand": "真龙",
      "name_cn": "真龙（甲天下中支）",
      "origin": "广西",
      "format": "中支",
      "rarity": 5,
      "base_score": 7,
      "image_url": "https://ciggies.app/api/img/products/2021092822512849.png"
    },
    {
      "id": "pack_2413",
      "type": "pack",
      "brand": "真龙",
      "name_cn": "真龙（海韵细支）",
      "origin": "广西",
      "format": "常规",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/20160608021133.png"
    },
    {
      "id": "pack_3681",
      "type": "pack",
      "brand": "真龙",
      "name_cn": "真龙（金韵）",
      "origin": "广西",
      "format": "常规",
      "rarity": 5,
      "base_score": 7,
      "image_url": "https://ciggies.app/api/img/products/2021012314245457.png"
    },
    {
      "id": "pack_3501",
      "type": "pack",
      "brand": "金圣",
      "name_cn": "金圣（智圣出山双中支）",
      "origin": "江西",
      "format": "中支",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/202303142227582180.png"
    },
    {
      "id": "pack_3560",
      "type": "pack",
      "brand": "金圣",
      "name_cn": "金圣（青瓷细支）",
      "origin": "江西",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202409012342553700.png"
    },
    {
      "id": "pack_3613",
      "type": "pack",
      "brand": "金圣",
      "name_cn": "金圣（乐神）",
      "origin": "江西",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202506161658144720.jpg"
    },
    {
      "id": "pack_3524",
      "type": "pack",
      "brand": "红塔山",
      "name_cn": "红塔山（峰中支）",
      "origin": "云南",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202310232326391020.png"
    },
    {
      "id": "pack_3591",
      "type": "pack",
      "brand": "中南海",
      "name_cn": "中南海（冰耀细支）",
      "origin": "北京",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202501142230330740.jpg"
    },
    {
      "id": "pack_3491",
      "type": "pack",
      "brand": "兰州",
      "name_cn": "兰州（中支飞天明珠）",
      "origin": "甘肃",
      "format": "中支",
      "rarity": 5,
      "base_score": 7,
      "image_url": "https://ciggies.app/api/img/products/202302162358216210.png"
    },
    {
      "id": "pack_3142",
      "type": "pack",
      "brand": "好猫",
      "name_cn": "好猫（中支金丝猴）",
      "origin": "陕西",
      "format": "中支",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/2019011222585214.png"
    },
    {
      "id": "pack_3575",
      "type": "pack",
      "brand": "好猫",
      "name_cn": "好猫（细支长乐吉祥）",
      "origin": "陕西",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202411162219540510.jpg"
    },
    {
      "id": "pack_3685",
      "type": "pack",
      "brand": "好猫",
      "name_cn": "好猫（长安）",
      "origin": "陕西",
      "format": "中支",
      "rarity": 5,
      "base_score": 7,
      "image_url": "https://ciggies.app/api/img/products/202405280113394500.jpg"
    },
    {
      "id": "pack_3517",
      "type": "pack",
      "brand": "天子",
      "name_cn": "天子（千里江山青绿中支）",
      "origin": "重庆",
      "format": "中支",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/202306122155410520.jpg"
    },
    {
      "id": "pack_3235",
      "type": "pack",
      "brand": "天子",
      "name_cn": "天子（金如意细支）",
      "origin": "重庆",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2019081920261161.png"
    },
    {
      "id": "pack_3648",
      "type": "pack",
      "brand": "天子",
      "name_cn": "天子（天福）",
      "origin": "重庆",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202510231854061670.png"
    },
    {
      "id": "pack_3297",
      "type": "pack",
      "brand": "将军",
      "name_cn": "将军（战神荣耀）",
      "origin": "山东",
      "format": "常规",
      "rarity": 5,
      "base_score": 7,
      "image_url": "https://ciggies.app/api/img/products/2020042402302766.png"
    },
    {
      "id": "pack_3078",
      "type": "pack",
      "brand": "将军",
      "name_cn": "将军（3G）",
      "origin": "山东",
      "format": "常规",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2018082620454742.png"
    },
    {
      "id": "pack_3354",
      "type": "pack",
      "brand": "人民大会堂",
      "name_cn": "人民大会堂（中支）",
      "origin": "辽宁",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2020111722173215.jpg"
    },
    {
      "id": "pack_3496",
      "type": "pack",
      "brand": "人民大会堂",
      "name_cn": "人民大会堂（红细支）",
      "origin": "辽宁",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202302220022074340.png"
    },
    {
      "id": "pack_3566",
      "type": "pack",
      "brand": "人民大会堂",
      "name_cn": "人民大会堂（光耀）",
      "origin": "辽宁",
      "format": "细支",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/202410202223042060.jpg"
    },
    {
      "id": "pack_3401",
      "type": "pack",
      "brand": "红河",
      "name_cn": "红河（快乐）",
      "origin": "云南",
      "format": "常规",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2021041410304554.png"
    },
    {
      "id": "pack_3039",
      "type": "pack",
      "brand": "红河",
      "name_cn": "红河（去野）",
      "origin": "云南",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2018071423075406.png"
    },
    {
      "id": "pack_3326",
      "type": "pack",
      "brand": "龙凤呈祥",
      "name_cn": "龙凤呈祥（好运来）",
      "origin": "四川",
      "format": "常规",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2020070922310852.png"
    },
    {
      "id": "pack_3175",
      "type": "pack",
      "brand": "龙凤呈祥",
      "name_cn": "龙凤呈祥（硬遇见）",
      "origin": "四川",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/2019050417112024.png"
    },
    {
      "id": "pack_3586",
      "type": "pack",
      "brand": "长白山",
      "name_cn": "长白山（心归细支）",
      "origin": "吉林",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202412300010258200.jpg"
    },
    {
      "id": "pack_3510",
      "type": "pack",
      "brand": "延安",
      "name_cn": "延安（中支红韵）",
      "origin": "陕西",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202305080006178990.jpg"
    },
    {
      "id": "pack_3641",
      "type": "pack",
      "brand": "牡丹",
      "name_cn": "牡丹（蓝彩细支）",
      "origin": "上海",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202509182224224480.png"
    },
    {
      "id": "pack_2012",
      "type": "pack",
      "brand": "红双喜",
      "name_cn": "红双喜（上海）",
      "origin": "上海",
      "format": "常规",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2021021015564674.png"
    },
    {
      "id": "pack_1024",
      "type": "pack",
      "brand": "大红鹰",
      "name_cn": "大红鹰（50版）",
      "origin": "浙江",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/20090701124339.jpg"
    },
    {
      "id": "pack_2176",
      "type": "pack",
      "brand": "庐山",
      "name_cn": "庐山（大红运）",
      "origin": "江西",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/20150603014703.jpg"
    },
    {
      "id": "pack_689",
      "type": "pack",
      "brand": "红梅",
      "name_cn": "红梅（软顺）",
      "origin": "云南",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/20070212144306.jpg"
    },
    {
      "id": "pack_3310",
      "type": "pack",
      "brand": "红金龙",
      "name_cn": "红金龙（软精品二代）",
      "origin": "湖北",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/2020051922082969.png"
    },
    {
      "id": "pack_1007",
      "type": "pack",
      "brand": "大前门",
      "name_cn": "大前门（硬）",
      "origin": "上海",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/20090414002718.jpg"
    },
    {
      "id": "pack_3489",
      "type": "pack",
      "brand": "冬虫夏草",
      "name_cn": "冬虫夏草（黄金盛世中支）",
      "origin": "内蒙古",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202302072333065210.png"
    },
    {
      "id": "pack_2459",
      "type": "pack",
      "brand": "恒大",
      "name_cn": "恒大（记忆1949）",
      "origin": "湖北",
      "format": "常规",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/20160720125041.png"
    },
    {
      "id": "pack_3040",
      "type": "pack",
      "brand": "红旗渠",
      "name_cn": "红旗渠（新版银河）",
      "origin": "河南",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/2018071601414384.png"
    },
    {
      "id": "pack_2576",
      "type": "pack",
      "brand": "黄果树",
      "name_cn": "黄果树（万里长征）",
      "origin": "贵州",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/20161125144955.png"
    },
    {
      "id": "pack_2032",
      "type": "pack",
      "brand": "都宝",
      "name_cn": "都宝（蓝莓细支）",
      "origin": "湖北",
      "format": "细支",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/2021011923312862.png"
    },
    {
      "id": "pack_3307",
      "type": "pack",
      "brand": "哈尔滨",
      "name_cn": "哈尔滨（老巴夺红中支）",
      "origin": "黑龙江",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2020051823034488.png"
    },
    {
      "id": "pack_3373",
      "type": "pack",
      "brand": "大青山",
      "name_cn": "大青山（硬昭君和亲）",
      "origin": "内蒙古",
      "format": "中支",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/2021012413554209.png"
    },
    {
      "id": "pack_1384",
      "type": "pack",
      "brand": "猴王",
      "name_cn": "猴王（紫）",
      "origin": "陕西",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/20101215011605.jpg"
    },
    {
      "id": "pack_3671",
      "type": "pack",
      "brand": "双喜·好日子",
      "name_cn": "双喜·好日子（Unknown）",
      "origin": "广东",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202602042054195730.jpg"
    },
    {
      "id": "pack_1057",
      "type": "pack",
      "brand": "芙蓉",
      "name_cn": "芙蓉（软橙）",
      "origin": "湖南",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/20090814230718.jpg"
    },
    {
      "id": "pack_2863",
      "type": "pack",
      "brand": "双喜",
      "name_cn": "双喜（金国喜细支）",
      "origin": "广东",
      "format": "细支",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/2017092113071851.png"
    },
    {
      "id": "pack_3478",
      "type": "pack",
      "brand": "泰山",
      "name_cn": "泰山（儒风双中支）",
      "origin": "山东",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202301022234201840.png"
    },
    {
      "id": "pack_2432",
      "type": "pack",
      "brand": "兰州",
      "name_cn": "兰州（细支珍品）",
      "origin": "甘肃",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/20160705232029.png"
    },
    {
      "id": "pack_3341",
      "type": "pack",
      "brand": "贵烟",
      "name_cn": "贵烟（贵中支）",
      "origin": "贵州",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2020092119444777.png"
    },
    {
      "id": "pack_2713",
      "type": "pack",
      "brand": "好猫",
      "name_cn": "好猫（细支招财猫）",
      "origin": "陕西",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2017050619124292.png"
    },
    {
      "id": "pack_3458",
      "type": "pack",
      "brand": "天子",
      "name_cn": "天子（黄中支）",
      "origin": "重庆",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/2022080823014501.png"
    },
    {
      "id": "pack_3495",
      "type": "pack",
      "brand": "人民大会堂",
      "name_cn": "人民大会堂（硬红细支）",
      "origin": "辽宁",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202302212342302380.png"
    },
    {
      "id": "pack_3289",
      "type": "pack",
      "brand": "延安",
      "name_cn": "延安（千年帝都中支）",
      "origin": "陕西",
      "format": "中支",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/202301032112393610.png"
    },
    {
      "id": "pack_3555",
      "type": "pack",
      "brand": "黄金叶",
      "name_cn": "黄金叶（大成细支）",
      "origin": "河南",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202406180054454040.png"
    },
    {
      "id": "pack_3502",
      "type": "pack",
      "brand": "恒大",
      "name_cn": "恒大（蓝金中支）",
      "origin": "湖北",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202303212351333000.jpg"
    },
    {
      "id": "pack_3627",
      "type": "pack",
      "brand": "冬虫夏草",
      "name_cn": "冬虫夏草（细支）",
      "origin": "内蒙古",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202508180020510580.png"
    },
    {
      "id": "pack_3500",
      "type": "pack",
      "brand": "金圣",
      "name_cn": "金圣（吉品中支）",
      "origin": "江西",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202303142214473320.jpg"
    },
    {
      "id": "pack_3558",
      "type": "pack",
      "brand": "黄山",
      "name_cn": "黄山（经典皖烟细支）",
      "origin": "安徽",
      "format": "细支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202407102230244460.jpg"
    },
    {
      "id": "pack_3471",
      "type": "pack",
      "brand": "中南海",
      "name_cn": "中南海（双中支北京）",
      "origin": "北京",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202211162028401930.jpg"
    },
    {
      "id": "pack_3146",
      "type": "pack",
      "brand": "红塔山",
      "name_cn": "红塔山（传奇细支）",
      "origin": "云南",
      "format": "细支",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/2019012222540162.jpg"
    },
    {
      "id": "pack_3663",
      "type": "pack",
      "brand": "牡丹",
      "name_cn": "牡丹（玄华双中）",
      "origin": "上海",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202601021102453820.png"
    },
    {
      "id": "pack_3633",
      "type": "pack",
      "brand": "娇子",
      "name_cn": "娇子（宽窄国宝之恋细支）",
      "origin": "四川",
      "format": "细支",
      "rarity": 5,
      "base_score": 7,
      "image_url": "https://ciggies.app/api/img/products/202509012326189300.jpg"
    },
    {
      "id": "pack_3643",
      "type": "pack",
      "brand": "长白山",
      "name_cn": "长白山（新圣境）",
      "origin": "吉林",
      "format": "中支",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/202509281904249570.jpg"
    },
    {
      "id": "pack_430",
      "type": "pack",
      "brand": "哈尔滨",
      "name_cn": "哈尔滨（祥和龙烟）",
      "origin": "黑龙江",
      "format": "常规",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/20051226112551.jpg"
    },
    {
      "id": "pack_372",
      "type": "pack",
      "brand": "哈尔滨",
      "name_cn": "哈尔滨（硬黄）",
      "origin": "黑龙江",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/20051226114606.jpg"
    },
    {
      "id": "pack_983",
      "type": "pack",
      "brand": "黄山",
      "name_cn": "黄山（蓝一品）",
      "origin": "安徽",
      "format": "常规",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/20090326141430.jpg"
    },
    {
      "id": "pack_887",
      "type": "pack",
      "brand": "黄山",
      "name_cn": "黄山（国宾迎客松）",
      "origin": "安徽",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/20080919022338.jpg"
    },
    {
      "id": "pack_33",
      "type": "pack",
      "brand": "中南海",
      "name_cn": "中南海（黑耀5mg）",
      "origin": "北京",
      "format": "常规",
      "rarity": 4,
      "base_score": 5,
      "image_url": "https://ciggies.app/api/img/products/2017050813435974.png"
    },
    {
      "id": "pack_32",
      "type": "pack",
      "brand": "中南海",
      "name_cn": "中南海（软精品）",
      "origin": "北京",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/20051214114647.jpg"
    },
    {
      "id": "pack_996",
      "type": "pack",
      "brand": "兰州",
      "name_cn": "兰州（吉祥16支）",
      "origin": "甘肃",
      "format": "常规",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/20090404040309.jpg"
    },
    {
      "id": "pack_926",
      "type": "pack",
      "brand": "兰州",
      "name_cn": "兰州（六味）",
      "origin": "甘肃",
      "format": "常规",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/20090217131651.jpg"
    },
    {
      "id": "pack_933",
      "type": "pack",
      "brand": "长白山",
      "name_cn": "长白山（德容天下）",
      "origin": "吉林",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/20090306133449.jpg"
    },
    {
      "id": "pack_928",
      "type": "pack",
      "brand": "长白山",
      "name_cn": "长白山（5mg）",
      "origin": "吉林",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/2021021406530792.png"
    },
    {
      "id": "pack_927",
      "type": "pack",
      "brand": "南京",
      "name_cn": "南京（九五）",
      "origin": "江苏",
      "format": "常规",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/20090219010432.jpg"
    },
    {
      "id": "pack_805",
      "type": "pack",
      "brand": "南京",
      "name_cn": "南京（古都）",
      "origin": "江苏",
      "format": "常规",
      "rarity": 5,
      "base_score": 7,
      "image_url": "https://ciggies.app/api/img/products/202401032344529050.png"
    },
    {
      "id": "pack_893",
      "type": "pack",
      "brand": "大青山",
      "name_cn": "大青山（软）",
      "origin": "内蒙古",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/20081111104000.jpg"
    },
    {
      "id": "pack_421",
      "type": "pack",
      "brand": "大青山",
      "name_cn": "大青山（红）",
      "origin": "内蒙古",
      "format": "常规",
      "rarity": 2,
      "base_score": 2,
      "image_url": "https://ciggies.app/api/img/products/20051025141201.jpg"
    },
    {
      "id": "pack_818",
      "type": "pack",
      "brand": "苏烟",
      "name_cn": "苏烟（铂晶）",
      "origin": "江苏",
      "format": "常规",
      "rarity": 3,
      "base_score": 3,
      "image_url": "https://ciggies.app/api/img/products/20080305204200.jpg"
    }
  ],
  "counterfeit_cards": [
    {
      "id": "fake_chunghwa",
      "type": "counterfeit",
      "brand": "中华",
      "name_cn": "假中华（硬）",
      "name_en": "Fake Chunghwa (Hard)",
      "origin": "上海",
      "format": "常规",
      "rarity": 5,
      "base_score": -5,
      "image_url": "",
      "flavor_cn": "包装精美但烟丝发黑，拉丝不均匀",
      "flavor_en": "Fancy packaging but dark tobacco with uneven threads"
    },
    {
      "id": "fake_panda",
      "type": "counterfeit",
      "brand": "熊猫",
      "name_cn": "假熊猫（经典）",
      "name_en": "Fake Panda (Classic)",
      "origin": "上海",
      "format": "常规",
      "rarity": 5,
      "base_score": -5,
      "image_url": "",
      "flavor_cn": "熊猫印歪了，眼神呆滞",
      "flavor_en": "Panda printed crooked with a blank stare"
    },
    {
      "id": "fake_furongwang",
      "type": "counterfeit",
      "brand": "芙蓉王",
      "name_cn": "假芙蓉王（硬）",
      "name_en": "Fake Furong Wang (Hard)",
      "origin": "湖南",
      "format": "常规",
      "rarity": 4,
      "base_score": -5,
      "image_url": "",
      "flavor_cn": "金边掉色，封口粗糙",
      "flavor_en": "Gold trim fading, rough seal"
    },
    {
      "id": "fake_1916",
      "type": "counterfeit",
      "brand": "黄鹤楼",
      "name_cn": "假黄鹤楼（1916）",
      "name_en": "Fake Yellow Crane Tower (1916)",
      "origin": "湖北",
      "format": "细支",
      "rarity": 5,
      "base_score": -5,
      "image_url": "",
      "flavor_cn": "防伪码一刮就没，钢印模糊",
      "flavor_en": "Anti-counterfeit code rubs off instantly, blurry stamp"
    },
    {
      "id": "fake_nanjing95",
      "type": "counterfeit",
      "brand": "南京",
      "name_cn": "假南京（九五）",
      "name_en": "Fake Nanjing (95)",
      "origin": "江苏",
      "format": "常规",
      "rarity": 4,
      "base_score": -5,
      "image_url": "",
      "flavor_cn": "字体间距不对，老烟民一眼就认出来",
      "flavor_en": "Wrong font spacing, veteran smokers spot it instantly"
    }
  ],
  "item_cards": [
    {
      "id": "item_zippo",
      "type": "item",
      "name_cn": "Zippo 打火机",
      "name_en": "Zippo Lighter",
      "effect": "highest_combo_plus5",
      "effect_cn": "你本轮分数最高的 combo +5",
      "effect_en": "Your highest combo this round +5"
    },
    {
      "id": "item_moutai",
      "type": "item",
      "name_cn": "茅台酒",
      "name_en": "Moutai Liquor",
      "effect": "both_plus4",
      "effect_cn": "选1位玩家，你俩各+4",
      "effect_en": "Pick a player, both of you +4"
    },
    {
      "id": "item_mahjong",
      "type": "item",
      "name_cn": "麻将桌",
      "name_en": "Mahjong Table",
      "effect": "old_friends_plus5",
      "effect_cn": "本轮同产地3张改为+13（原+8）",
      "effect_en": "Same-origin 3-card combo becomes +13 (was +8)"
    },
    {
      "id": "item_casino",
      "type": "item",
      "name_cn": "澳门赌场",
      "name_en": "Macau Casino",
      "effect": "coin_flip",
      "effect_cn": "抛硬币：正面+10，反面-5",
      "effect_en": "Coin flip: heads +10, tails -5"
    },
    {
      "id": "item_certificate",
      "type": "item",
      "name_cn": "假烟鉴定书",
      "name_en": "Authentication Certificate",
      "effect": "immune_counterfeit",
      "effect_cn": "免疫1张假烟的-5分",
      "effect_en": "Immune to one counterfeit card's -5 penalty"
    },
    {
      "id": "item_blackmarket",
      "type": "item",
      "name_cn": "黑市通行证",
      "name_en": "Black Market Pass",
      "effect": "retrieve_discard",
      "effect_cn": "从弃牌堆捞回1张",
      "effect_en": "Retrieve 1 card from the discard pile"
    },
    {
      "id": "item_smuggling",
      "type": "item",
      "name_cn": "走私渠道",
      "name_en": "Smuggling Route",
      "effect": "swap_card",
      "effect_cn": "与任意玩家交换1张已选的牌",
      "effect_en": "Swap 1 kept card with any player"
    },
    {
      "id": "item_fine",
      "type": "item",
      "name_cn": "控烟办罚单",
      "name_en": "Smoking Ban Fine",
      "effect": "halve_highest_combo",
      "effect_cn": "选1位玩家，其最高combo减半（向下取整）",
      "effect_en": "Pick a player, halve their highest combo (round down)"
    }
  ]
};
